name: Create tag

on:
  workflow_dispatch:

jobs:
  make-tag:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          sparse-checkout: |
            package.json
          sparse-checkout-cone-mode: false
      # Read package.json
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      # Print out version
      - run: echo "version - ${{ steps.info.outputs.version }}"
      #Create and push tag
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.info.outputs.version }}
          tag_exists_error: false
          message: "Latest release"
      





            
